ROOT:
  command_path:
  - /home/maarten/.dodo_commands/default_project/commands/*
  - ${/ROOT/project_dir}/commands
  version: 1.0.0
  aliases:
    run-writer: writer.mk runserver
    run-reader: reader.mk runserver

LAYER_GROUPS:
  server:
  - writer:
      inferred_by: [mk-greet]
  - reader

LAYERS:
- docker.yaml

MENU:
  commands:
    server:
    - dodo writer.mk runserver
    - dodo reader.mk runserver

