version : '3'

services :
  writer:
    image: python:3.7-alpine-make
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./writer:/tmp/app
      - ./time.log:/tmp/time.log
    working_dir: /tmp/app
    command: make runserver

  reader:
    depends_on: [writer]
    image: python:3.7-alpine-make
    volumes:
      - ./reader:/tmp/app
      - ./time.log:/tmp/time.log
    working_dir: /tmp/app
    command: make runserver
